name: linkly
description: "Linkly - Digital Business Card & Networking App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_messaging: ^14.7.10
  firebase_analytics: ^10.7.4
  firebase_crashlytics: ^3.4.9
  
  # Google Services
  google_sign_in: ^6.1.6
  
  # UI & Navigation
  cupertino_icons: ^1.0.8
  go_router: ^12.1.3
  
  # State Management
  provider: ^6.1.1
  riverpod: ^2.4.9
  
  # Camera & Media
  camera: ^0.10.5+5
  image_picker: ^1.0.4
  qr_code_scanner: ^1.0.1
  
  # Location
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  
  # Maps
  google_maps_flutter: ^2.5.0
  
  # Networking
  http: ^1.1.2
  dio: ^5.4.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  
  # UI Components
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  lottie: ^2.7.0
  
  # Utils
  intl: ^0.19.0
  url_launcher: ^6.2.2
  share_plus: ^7.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
  